---
title: "COVID-19 in Latin America"
subtitle: "UNC Gillings School of Global Public Health"
author: "Jesus E. Vazquez, PhD Student Biostatistics"
date: "3/18/2020"
output: html_document
---

## Introduction

The purpose of this analysis is to determine the extent at which COVID-19, better known as Coronavirus, has progressed in Latin America. Not only is monitoring COVID-19 important to help local and federal Latin America governments make better informed decisions, but it is neccesary due great amount of social disparities that will tremendously worsen the impact of the virus in the health of these communities. In this report we will present initial statistics and graphical illustrations of the current development of COVID-19 and future projections in Latin America. 

## Methods

Scatterplots with the counts of cases will be use to illustrate the progression of the virus, with a comparison to a poisson distribution derived by the current trends. An ARIMA will be used to predict and forecast the spread of the virus using time-series analysis.

## Results

### Importing, Cleaning Data, and Generating Plots

Data was provided by the Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE), ESRI Living Atlas Team and the Johns Hopkins University Applied Physics Lab (JHU APL) and update these data daily from information provided by the WHO, US and China CDC, among other worldwide organizations. [github](https://github.com/CSSEGISandData/COVID-19)

```{R, message = FALSE, warning = FALSE}
library(tidyverse)
library(reshape2)

# Reading and subsetting data
mydfcases <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv") %>%
  melt(id.vars=c("Province.State", "Country.Region", "Lat", "Long")) %>%
  rename("Area"= "Province.State", "Country"="Country.Region", "Count" = 'value', 'Date' = 'variable') %>%
  mutate(Date = sub('X', '', Date)) %>%
  mutate(Date = as.Date(Date,"%m.%d.%Y"))

mydfcases <- aggregate(mydfcases$Count, by=list(mydfcases$Country, mydfcases$Date), FUN=sum) %>%
  rename("Country"="Group.1","Date"="Group.2", "Count"="x")
```

```{R}
# Comparing againts Poisson Random Variable
country = mydfcases %>% subset(Country %in% c("Mexico") & Count > 0)
num_days = as.numeric(max(country$Date) - min(country$Date))
num_total_cases = max(country$Count)
lamba_hat = num_total_cases/num_days
country$expected = ppois(0:num_days, lambda = lamba_hat)*num_total_cases

# Plotting Agaist Distribution 
ggplot(country, aes(x=Date)) +  
  geom_text(aes(x = (max(Date)+2), y = max(Count), label = "Actual"), colour = 'red') + 
  geom_line(aes(y=Count), colour="red")  + 
  geom_text(aes(x = (max(Date)+2), y = max(expected), label = "Expected"), colour = 'black') +
  geom_line(aes(y=expected), colour="black") +  
  labs(title = 'Expected vs Actual COVID-19 Cases, Mexico', subtitle = 'Approximation with Poisson Model', y = 'Cases', x= '')
```

## Model Training and Prediction using Timeseries

```{R, message = FALSE, warning = FALSE}
library(forecast)

myforecast <- auto.arima(country$Count) %>% 
  forecast() %>% 
  as.data.frame() %>%
  rename(Count="Point Forecast") %>%
  subset(select=c("Count"))

max.date = max(country$Date) + dim(myforecast)[1]
myforecast$Date <- seq(as.Date(max(country$Date))+1, as.Date(max.date), by="days")
myforecast$Type <- "forecast" 
myforecast <- myforecast[1:5,]

#Merging datasets 
country$Type <- 'actual'
myforecast$Country <- country$Country[1]
mydata <- full_join(country, myforecast)

#Plot
ggplot(mydata, aes(x=Date, y = Count, colour = Type, label = Count)) +  
  theme_minimal() +
  geom_point() + 
  geom_line() +
  geom_text(aes(label=ifelse(Type=='forecast',as.character(Count),'')),hjust=1.5,vjust=0) +
  scale_x_date(date_labels = "%d %b", date_breaks = '4 day') +
  labs(y="Number of Cases", x='', title = 'Number of COVID-19 Reported Cases, Mexico', subtitle = 'Actual and Forecast using ARIMA Timeseries Model, 5 Day Projection')
```


